CREATE TABLE IF NOT EXISTS public.tb_person(
    id_person integer GENERATED BY DEFAULT AS IDENTITY,
    first_name character varying(255),
    last_name character varying(255),
    email character varying(400),
    CONSTRAINT PK_Person PRIMARY KEY (id_person)
);